name: Deploy Scott's Web Architecture

on:
  push:
    branch:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Navigate to Terraform Folder
        run: cd terraform && ls
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Initialization
        run: terraform init
      - name: Terraform Plan
        run: terraform plan