name: Deploy Scott's Web Architecture

on:
  workflow_dispatch:
  push:
    branch:
      - main

env:
  REACT_APP_API_KEY: ${{ secrets.API_KEY }}
  REACT_APP_API_URL: ${{ secrets.API_URL }}

jobs:
  terraform:
    name: "Deploy Scott's Website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.5
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
      - name: Terraform Validate
        run: terraform validate
      - name: Terrform Apply
        run: terraform apply -auto-approve
      - name: Compile Web Application
        run: npm install && npm run build
      - name: Deploy App Build to S3 Bucket
        run: aws s3 sync ./build/ s3://www.scottmchenry.net --delete
      - name: Invalidating AWS CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"